#!/usr/bin/expect -f
set timeout 20
set password "Eash@2005"
spawn ssh -p 65002 u856184323@82.25.120.218 "mysql -u u856184323_CroppingtoolID -p'Eash@2005' u856184323_IDCroppingtool -e 'ALTER TABLE projects ADD COLUMN design_state LONGTEXT DEFAULT NULL;'"
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}
